chrs:                                                                           
	- chr1                                                                   
	- chr2                                                                   
	- chr3                                                                   
	- chr4                                                                   
	- chr5                                                                   
	- chr6                                                                   
	- chr7                                                                   
	- chr8                                                                   
	- chr9                                                                   
	- chr10                                                                  
	- chr11                                                                  
	- chr12                                                                  
	- chr13                                                                  
	- chr14                                                                  
	- chr15                                                                  
	- chr16                                                                  
	- chr17                                                                  
	- chr18                                                                  
	- chr19                                                                  
	- chr20                                                                  
	- chr21                                                                  
	- chr22                                                                  
                                                                                
sv_types:
	- deletions
	- inversions
	- tandemDups
	- MEIs

ref_overlap_files:
	-  
#mei_types:
#       - MEIs

                                                                                
infile_dir: '../tests'
out_files_dir: '../tests'
temp_files_dir: '../tests'
                               
